import {narrative,prologues} from './story.js';
import {ROLES,KEY,fresh,normalize,complete,counts,keyIndex,nextId} from './engine.js';
import {worlds,links,sources} from './worlds.js';
const app=document.querySelector('#app');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=fresh(),storageOK=true;try{state=normalize(JSON.parse(localStorage.getItem(KEY)));}catch{storageOK=false;}
let data,route='home',current='h1-s1',phase='story',wrong=null,ordered=[],pairs={},selectedPair=null,toolFeedback='',timer;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;toast('此瀏覽器無法儲存；請到行動手札匯出備份。');}}
function toast(t){clearTimeout(timer);const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');timer=setTimeout(()=>el.classList.remove('show'),5000);}
function role(){return state.role||'teen';}
function getStage(id=current){for(const h of data.habits){const s=h.stages.find(s=>s.id===id);if(s)return {h,s,w:worlds[h.id-1],v:s.versions[role()]};}return null;}
function portrait(i,cls=''){return `<div class="mentor ${cls}" role="img" aria-label="${esc(worlds[i].mentor)}，頭身比例一比一的 Q 版插畫" style="--mx:${(i%4)*100/3}%;--my:${i<4?0:100}%"></div>`;}
function go(view){route=view;phase='story';wrong=null;render();window.scrollTo({top:0});}
function enter(id){if(!state.role){go('roles');return;}current=id;state.last[role()]=id;save();route='stage';phase='story';wrong=null;ordered=[];pairs={};selectedPair=null;toolFeedback='';render();}
function stageDone(id){return state.completed[role()].includes(id);}
function render(){document.querySelector('#role-label').textContent=state.role?ROLES[role()].short+'旅人':'選擇身分';document.body.dataset.view=route;document.body.dataset.phase=phase;document.querySelector('.landscape').style.backgroundPosition=route==='stage'?`${25+(Number(current.match(/s(\d+)/)?.[1]||1)*5)}% center`:'center';if(route==='home'||route==='roles')home();else if(route==='prologue')prologue();else if(route==='map')map();else if(route==='journal')journal();else if(route==='guide')guide();else stage();}
function home(){app.innerHTML=`<section class="home hero"><div class="welcome-grid"><div class="home-copy"><div class="eyebrow">八位臺灣同行者 · 八枚羅盤碎片 · 你的英雄之旅</div><h1>方向弄丟了？<br><span>我們陪你找回來。</span></h1><p class="lead">一場風暴，把心之羅盤吹散到八個國度。<br>跟著小老師走進故事，從生活的小選擇找回方向。</p></div><div class="welcome-party" aria-label="小老師在森林入口迎接你"><p class="welcome-speech">「帶上你的疑問就好。<br>這趟路，我們一起走。」<small>徐生明・你的第一位同行者</small></p>${portrait(0,'welcome-first')}${portrait(4,'welcome-second')}${portrait(1,'welcome-third')}</div></div><p class="eyebrow role-invitation">選擇你的身分，打開屬於你的第一封信</p><div class="role-grid">${Object.entries(ROLES).map(([k,r],i)=>`<button class="role-card" data-role="${k}"><span class="role-icon">${['✧','⌁','✦'][i]}</span><b>${r.name}</b><span>${r.theme}</span><small>${state.completed[k].length}/80 關 · 選擇這條路線 ↗</small></button>`).join('')}</div>${state.role?`<button class="primary continue" data-stage="${state.last[role()]}">接續${ROLES[role()].short}旅程 →</button>`:''}<div class="home-companions"><p>八境的同行者，都在前方等你</p><div>${worlds.map((w,i)=>`<figure>${portrait(i)}<figcaption>${w.mentor}</figcaption></figure>`).join('')}</div></div><p class="small-note">選擇 · 配合 · 排序 · 生活行動　／　人物對話為原創故事，不是歷史引言</p></section>`;}
function prologue(){app.innerHTML=`<section class="prologue"><div class="prologue-copy"><p class="eyebrow">${ROLES[role()].name} · 序章</p><h1>那封沒有署名的信</h1><p>${prologues[role()]}</p><p>八位小老師各守著一段路。每一境有十個路口；你要幫助旅隊，也會在羅盤裡遇見自己的生活。</p><div class="dialogue-bottom"><button data-nav="map">先看看八境旅圖</button><button class="primary" data-stage="${state.last[role()]}">提起燈，走進故事 →</button></div></div>${portrait(0,'prologue-mentor')}</section>`;}
function map(){if(!state.role){home();return;}const total=counts(state,role());app.innerHTML=`<section class="map-page"><div class="page-heading"><div><p class="eyebrow">${ROLES[role()].name} · 由內而外的英雄之旅</p><h1>你的八境旅圖</h1><p>風暴吹散了羅盤。每一境，都找回一種面對生活的力量。</p></div><div class="total"><strong>${total}<small>/80</small></strong><span>情境已過關 · 還有 ${80-total} 關</span><progress value="${total}" max="80"></progress></div></div><div class="world-grid">${data.habits.map((h,i)=>{const done=counts(state,role(),h.id);return `<article class="world-card"><div class="world-art" style="--wx:${i%4*100/3}%;--wy:${i<4?0:100}%"></div><div class="world-copy"><span class="eyebrow">第 ${h.id} 境 · ${done}/10 小關</span><h2>${worlds[i].name}</h2><p>${esc(h.title)}</p><div class="dots" aria-label="小關進度">${h.stages.map((s,j)=>`<button title="${esc(s.title)}：${stageDone(s.id)?'已過關':'待探索'}" aria-label="第 ${j+1} 關 ${esc(s.title)} ${stageDone(s.id)?'已過關':'待探索'}" class="dot ${stageDone(s.id)?'done':''}" data-stage="${s.id}">${stageDone(s.id)?'✓':j+1}</button>`).join('')}</div><button class="world-enter" data-stage="${h.stages.find(s=>!stageDone(s.id))?.id||h.stages[0].id}">${done===10?'重訪這一境':'走進故事'} <span>→</span></button></div></article>`;}).join('')}</div><p class="small-note">八境都可自由進入；建議依序練習。綠色勾號代表情境過關，不代表生活中已做到。</p></section>`;}
function stage(){const {h,s,w,v}=getStage();const num=h.stages.indexOf(s)+1,done=counts(state,role(),h.id),story=narrative(h,s,v,role());app.innerHTML=`<section class="scene"><div class="scene-art" aria-hidden="true" style="--wx:${(h.id-1)%4*100/3}%;--wy:${h.id<=4?0:100}%;--pan:${40+num*2}%"></div><div class="scene-shade"></div><div class="scene-heading"><p class="eyebrow">${ROLES[role()].short}旅人 / 第 ${h.id} 境・${w.name}</p><h1>${esc(story.place)}</h1><p class="chapter-subtitle">第 ${num} 幕 · ${esc(s.title)}</p><div class="progress-label">本境已過 ${done}/10 小關 · 目前第 ${num}/10 關 · 尚有 ${10-done} 關</div><progress value="${done}" max="10" aria-label="本境完成進度"></progress><button class="text-button" data-nav="map">查看已完成與未完成的關卡 ↗</button></div>${portrait(h.id-1,'scene-mentor')}<div class="dialogue"><div class="speaker"><span>${w.mentor}</span><small>${w.job} · 陪伴小老師</small><span class="step-name">${phase==='story'?'① 故事':phase==='quiz'?'② 情境判斷':phase==='tool'?'③ 動手練習':phase==='ending'?'旅程回聲':num%3===0?'④ 生活行動':'③ 生活行動'}</span></div>${phase==='story'?`<p class="story-intro">${esc(story.arrival)}</p><p class="scene-text">${esc(story.event)}</p><div class="life-window"><small>${story.bridge}</small><p>${esc(v.scene)}</p></div><div class="dialogue-bottom"><span class="concept">這一關，練習 ${esc(s.concept)}</span><button class="primary" data-act="quiz">我會怎麼選？ →</button></div>`:phase==='quiz'?quiz(v):phase==='tool'?tool(w,num):phase==='action'?action(v,story):`<h2>${num===10?(done===10?'這一境的故事，走到這裡。':'最後路口，也能回頭探索。'):'把這一步帶回生活。'}</h2><p>${num===10?(done<10?`你已走到本境最後一個路口；${w.name}目前完成 ${done}/10 關，還有 ${10-done} 關可以回訪。`:h.id===8&&counts(state,role())<80?`你已走完心聲燈塔，整段旅程還有 ${80-counts(state,role())} 關等你回訪。把找到的方向先帶回生活，再慢慢補齊羅盤。`:w.ending):esc(v.explanation)}</p><div class="story-next"><span class="eyebrow">故事還在往前</span><p>${esc(story.next)}</p></div><p class="small-note">行動已記在手札；願意試試與已經做過，會分開顯示。</p><div class="dialogue-bottom"><button data-nav="journal">看看行動手札</button><button class="primary" ${nextId(s.id)?`data-stage="${nextId(s.id)}"`:'data-nav="map"'}>${nextId(s.id)?'前往下一個路口':'回看完整旅程'} →</button></div>`}</div></section>`;if(phase!=='story')requestAnimationFrame(()=>app.querySelector('.dialogue')?.scrollIntoView({block:'nearest',behavior:'smooth'}));}
function quiz(v){return `<p class="quiz-scene">${esc(v.scene)}</p><h2>${esc(v.prompt)}</h2><div class="options">${v.options.map((o,i)=>`<button class="option ${wrong===i?'incorrect':''}" data-answer="${i}" ${wrong!==null?'disabled':''}><kbd>${'ABCD'[i]}</kbd><span>${esc(o)}</span><small>${['← / 1','↑ / 2','↓ / 3','→ / 4'][i]}</small></button>`).join('')}</div>${wrong!==null?`<div class="feedback" role="alert"><b>停一下，看看這個選擇的影響。</b><p>${esc(v.explanation)}</p><button data-act="retry">帶著線索再試一次</button></div>`:'<p class="key-hint">方向鍵 ← ↑ ↓ → 或數字 1–4 選答。答對直接進入下一步；答錯先看解析。</p>'}`;}
function tool(w,num){if(num%2===0)return `<h2>把三張行動卡排成可執行的順序</h2><p>先做什麼，才能讓下一步發生？依序點選卡片。</p><ol class="order-result">${ordered.map(i=>`<li>${esc(w.steps[i])}</li>`).join('')}</ol><div class="tool-options">${[2,0,1].map(i=>`<button data-order="${i}" ${ordered.includes(i)?'disabled':''}>${esc(w.steps[i])}</button>`).join('')}</div><p role="status">${toolFeedback}</p><div class="dialogue-bottom"><button data-act="reset-tool">重新排列</button><button class="primary" data-act="check-tool" ${ordered.length!==3?'disabled':''}>確認順序 →</button></div>`;
return `<h2>把概念與生活裡的意思配成一對</h2><p>先點左邊概念，再點右邊說明。</p><div class="matching"><div>${w.pairs.map(([a],i)=>`<button class="${selectedPair===i?'selected':''}" data-left="${i}" ${pairs[i]!==undefined?'disabled':''}>${esc(a)} ${pairs[i]!==undefined?'✓':''}</button>`).join('')}</div><div>${[1,2,0].map(i=>`<button data-right="${i}" ${Object.values(pairs).includes(i)?'disabled':''}>${esc(w.pairs[i][1])}</button>`).join('')}</div></div><p role="status">${toolFeedback||'每個概念都有一個對應的說明。'}</p>${Object.keys(pairs).length===3?'<button class="primary" data-act="action">帶回生活 →</button>':''}`;}
function action(v,story){return `<div class="story-resolution"><span class="eyebrow">旅隊的故事回聲</span><p>${esc(story.resolution)}</p><small>這是旅途中這次選擇的結果。生活裡也可能需要嘗試與調整。</small></div><span class="eyebrow">答題過關了；生活練習才正要開始。</span><h2>未來 48 小時，試一個小行動。</h2><p class="action-prompt">${esc(v.action)}</p><p>不用交出私事，也不需要證明自己很完美。選一個符合現在的狀態。</p><div class="action-choices"><button class="primary" data-action="planned">我想找機會試試</button><button data-action="adjust">我需要縮小或調整這一步</button><button data-action="private">先放在心裡，這次不分享</button></div><details><summary>剛剛的選擇，為什麼有幫助？</summary><p>${esc(v.explanation)}</p></details>`;}
function journal(){if(!state.role){home();return;}const rows=data.habits.flatMap(h=>h.stages).filter(s=>stageDone(s.id)||state.actions[role()][s.id]);const labels={planned:'想找機會試試',tried:'已嘗試・自己回報',adjust:'想調整這一步',private:'這次不分享'};app.innerHTML=`<section class="paper-page"><p class="eyebrow">${ROLES[role()].name} · 私人的生活紀錄</p><h1>行動手札</h1><p>情境過關 ${counts(state,role())}/80 · 實際嘗試 ${Object.values(state.actions[role()]).filter(x=>x==='tried').length} 次（自行回報）</p><p>這裡記錄你願意嘗試的事，不替人格打分數。進度只存在此瀏覽器，換裝置可匯出／匯入。</p>${!storageOK?'<p class="warning">目前無法使用瀏覽器儲存，請先匯出備份。</p>':''}<div class="backup"><button data-act="export">匯出旅程備份 ↓</button><label class="button">匯入備份<input type="file" id="import" accept="application/json" hidden></label></div>${rows.length?rows.map(s=>`<article class="journal-entry"><span class="eyebrow">${s.id.replace('h','習慣 ').replace('-s','・第 ')} 關</span><h2>${esc(s.title)}</h2><p>${esc(s.versions[role()].action)}</p><p class="status">${labels[state.actions[role()][s.id]]||'已過關・還沒選擇行動'}</p><div class="journal-buttons"><button data-practice="${s.id}">我在生活中試過了</button><button data-revisit="${s.id}">再想想這一步</button><button data-stage="${s.id}">重訪故事</button></div></article>`).join(''):'<div class="empty"><h2>你的第一頁，還留著空白。</h2><p>從第一個路口開始，帶一個小行動回來。</p><button class="primary" data-stage="h1-s1">走進選擇之森 →</button></div>'}</section>`;}
function guide(){app.innerHTML=`<section class="paper-page"><p class="eyebrow">一起學習，也一起保留提問</p><h1>小老師與備課室</h1><p>這八位臺灣代表人物已離世。本站以其生平事蹟作為學習引子；人物對話與習慣關卡是原創教學設計，並非本人說過的話，也不代表人物曾教授柯維理論。</p><details open><summary>給老師：40 分鐘怎麼帶？</summary><ol><li>5 分鐘：先看情境，讓學生私下做選擇。</li><li>10 分鐘：兩人比較理由，不要求分享自己的家庭經驗。</li><li>15 分鐘：玩關卡與配合／排序工具，討論哪些需要沒被看見。</li><li>8 分鐘：把生活行動縮小到可做的一步，可以選擇不分享。</li><li>2 分鐘：邀請 48 小時內向一位信任的人說明這個概念；下次回來談嘗試後想改什麼。</li></ol><p>國小版以中高年級可獨立閱讀為預設，低年級可由成人共讀，從具體物品、遊戲與生活照顧入門；國中版聚焦同儕、分組與課業期待；成人版聚焦工作、家庭與公共生活。不以闖關數推論品格或學期成績。</p></details><details><summary>如果學生說：「這只是叫我乖吧？」</summary><p>可以回：「你可以拒絕，也可以提出不同想法。我們練的是看見選擇與後果，不是猜老師喜歡的答案。哪個選項讓你覺得被要求委屈？我們一起看。」</p><p>主動積極不等於忍受傷害；遇到威脅、霸凌或不安全的情況，先離開並向可信任的大人或適當支援求助。</p></details><div class="mentor-grid">${worlds.map((w,i)=>`<article>${portrait(i)}<h2>${w.mentor}</h2><small>${w.en} · ${w.years}</small><p>${w.bio}</p><a href="${w.source}" target="_blank" rel="noreferrer">閱讀人物史料 ↗</a></article>`).join('')}</div><h2>概念來源與延伸練習</h2><p>第八個習慣是找到自己的聲音，也幫助他人找到聲音。本站原創情境以才能、熱情、需要與良知四個方向引導探索；不是官方認證課程。</p>${[...sources,...links].map(l=>`<p><a href="${l.url}" target="_blank" rel="noreferrer">${l.title} ↗</a>${l.note?` · ${l.note}`:''}</p>`).join('')}<p>設計參考大乃老師既有 Habit Quest 的情境辨識、Seven Habits Quest 的行為選擇，以及專注道場的實踐紀錄方式，未匯入學生作業或個人資料。</p></section>`;}
function choose(i){if(route!=='stage'||phase!=='quiz'||wrong!==null)return;const {v}=getStage();if(i===v.answer){toast('你辨認出這個情境的關鍵，接著把它化成行動。');phase=Number(current.split('-s')[1])%3===0?'tool':'action';ordered=[];pairs={};selectedPair=null;toolFeedback='';}else wrong=i;render();}
document.addEventListener('click',e=>{if(!data)return;const b=e.target.closest('button,a,label');if(!b)return;if(b.matches('.brand')){e.preventDefault();go('home');}if(b.dataset.nav)go(b.dataset.nav);if(b.dataset.role){state.role=b.dataset.role;save();go('prologue');}if(b.dataset.stage)enter(b.dataset.stage);if(b.dataset.answer!==undefined)choose(+b.dataset.answer);if(b.dataset.action){state=complete(state,role(),current);state.actions[role()][current]=b.dataset.action;save();phase='ending';render();}if(b.dataset.practice){state.actions[role()][b.dataset.practice]='tried';save();render();toast('已記下你的嘗試。下次也可以調整做法。');}if(b.dataset.revisit){state.actions[role()][b.dataset.revisit]='adjust';save();render();}if(b.dataset.order!==undefined&&!ordered.includes(+b.dataset.order)){ordered.push(+b.dataset.order);render();}if(b.dataset.left!==undefined){selectedPair=+b.dataset.left;render();}if(b.dataset.right!==undefined){if(selectedPair===null){toolFeedback='先選一個左邊的概念。';}else if(selectedPair===+b.dataset.right){pairs[selectedPair]=selectedPair;selectedPair=null;toolFeedback='這一對配起來了。';}else toolFeedback='再比較看看：這個概念想描述的是什麼？';render();}const a=b.dataset.act;if(a==='quiz'){phase='quiz';render();}if(a==='retry'){wrong=null;render();}if(a==='action'){phase='action';render();}if(a==='reset-tool'){ordered=[];toolFeedback='';render();}if(a==='check-tool'){if(ordered.join(',')==='0,1,2'){phase='action';}else toolFeedback='先理解情況與需要，再決定行動。可以重新排列試試。';render();}if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='心之羅盤-旅程備份.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
document.addEventListener('keydown',e=>{if(e.repeat||e.altKey||e.ctrlKey||e.metaKey||e.target.matches('input,textarea,select,[contenteditable="true"]'))return;const i=keyIndex(e.key);if(i!==undefined&&route==='stage'&&phase==='quiz'&&wrong===null){e.preventDefault();choose(i);}});
document.addEventListener('change',async e=>{if(e.target.id!=='import')return;try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error();const raw=JSON.parse(await file.text());if(raw.version!==1||!raw.completed||!raw.actions)throw Error();const incoming=normalize(raw);for(const r of Object.keys(ROLES)){state.completed[r]=[...new Set([...state.completed[r],...incoming.completed[r]])];state.actions[r]={...incoming.actions[r],...state.actions[r]};}save();render();toast('備份已合併，原本的進度也保留了。');}catch{toast('無法讀取這份備份，原進度沒有變動。');}});
try{const res=await fetch('curriculum.json');if(!res.ok)throw Error();data=await res.json();render();}catch{app.innerHTML='<section class="paper-page"><h1>旅圖暫時沒有展開</h1><p>教材載入失敗，請確認連線後重新整理。既有進度仍保留在此瀏覽器。</p></section>';}
