export const worlds=[
{name:'選擇之森',mentor:'哈莉特・塔布曼',en:'Harriet Tubman',years:'約 1822–1913',job:'自由行動者',bio:'曾協助受奴役者走向自由，持續為他人的安全與自由行動。',source:'https://www.nps.gov/people/harriet-tubman.htm',intro:'風把路標吹亂了。先別追著風跑，試著找到你腳下能走的一步。',ending:'你找回第一枚羅盤碎片：外面的風未必會停，但回應可以從自己開始。下一站，試著決定要前往哪裡。',steps:['辨認發生的事與自己的感受','停一下，找出能影響的一步','選擇合乎原則的回應並付諸行動'],pairs:[['關注圈','我在意，卻不能直接決定的事'],['影響圈','我能採取行動影響的事'],['主動積極','在刺激與回應之間做選擇']]},
{name:'願景星臺',mentor:'凱瑟琳・強森',en:'Katherine Johnson',years:'1918–2020',job:'數學家',bio:'為美國太空任務計算飛行軌道，參與載人太空飛行的重要計算工作。',source:'https://science.nasa.gov/people/katherine-johnson/',intro:'星臺的望遠鏡指向許多方向。先描繪旅程結束時希望留下的樣子，再選一條路。',ending:'羅盤有了方向。你不用一次決定一輩子，只要讓眼前的選擇更靠近重視的事。接著，把方向放進日常。',steps:['想像希望留下的結果與影響','辨認自己重視的原則與角色','倒推現在能開始的行動'],pairs:[['使命','我重視什麼，以及想如何貢獻'],['角色','生活中需要照顧的不同責任'],['以終為始','先想清楚方向，再決定行動']]},
{name:'要事工坊',mentor:'班傑明・富蘭克林',en:'Benjamin Franklin',years:'1706–1790',job:'作家與發明家',bio:'從事出版、科學實驗與公共事務，也曾記錄自己的生活安排。',source:'https://www.nps.gov/inde/learn/historyculture/people-franklin-traits.htm',intro:'工坊的鐘聲催促著每個人。桌上有大石頭與細沙：你願意先為什麼留位置？',ending:'你為重要的事留了位置，也留下休息的空間。羅盤提醒你：生活不是把每分鐘塞滿。下一站要和他人一起走。',steps:['依重視的方向找出重要的事','把重要但不急迫的事排入時間','處理急事並調整不必要的要求'],pairs:[['第一象限','重要且急迫，需要即時處理'],['第二象限','重要不急迫，需要主動安排'],['第三象限','急迫不重要，需要協商界線']]},
{name:'雙贏廣場',mentor:'愛蓮娜・羅斯福',en:'Eleanor Roosevelt',years:'1884–1962',job:'人權倡議者',bio:'參與聯合國人權工作，致力於人權與公共服務。',source:'https://www.nps.gov/people/eleanor-roosevelt.htm',intro:'廣場上的人都想被聽見。你的需要值得被照顧，別人的也一樣。先找出彼此真正要的是什麼。',ending:'廣場不再只有誰輸誰贏。你學會兼顧雙方，也保留談不攏時暫不合作的自由。下一站，練習聽懂彼此。',steps:['說清自己的需要與界線','理解對方的需要與限制','找互利方案，否則暫不合作'],pairs:[['勇氣','清楚表達自己的需要與界線'],['體諒','認真考慮對方的需要'],['暫不合作','無法互利時不強迫成交']]},
{name:'傾聽街角',mentor:'弗雷德・羅傑斯',en:'Fred Rogers',years:'1928–2003',job:'兒童節目創作者',bio:'創作《羅傑斯先生的鄰居們》，重視孩子的感受與人際關係。',source:'https://misterrogers.org/about-fred-rogers/',intro:'街角的長椅空出一個位置。先把自己的答案放旁邊，聽一聽對方正在經歷什麼。',ending:'你練習了理解，也練習讓自己被理解。傾聽不是放棄立場，而是讓對話有機會繼續。帶著這份理解去創造新方法。',steps:['先聽對方的觀點與感受','用自己的話確認是否理解','再清楚表達自己的需要'],pairs:[['同理','理解感受與觀點，不必同意'],['確認理解','詢問自己的理解是否正確'],['解己','清楚表達自己的想法與需要']]},
{name:'共創實驗室',mentor:'葛麗絲・霍普',en:'Grace Hopper',years:'1906–1992',job:'電腦科學先驅',bio:'投入早期電腦程式設計與程式語言發展，推動人與電腦溝通的方法。',source:'https://www.history.navy.mil/content/history/nhhc/browse-by-topic/people/namesakes/grace-hopper.html',intro:'實驗室收到兩張完全不同的設計圖。先別急著投票；差異也可能是新發明的材料。',ending:'你不只選了誰的方法，而是讓不同觀點長出新的選項。羅盤更完整了，但旅人也需要補充能量。',steps:['理解雙方差異及背後需要','一起提出原先沒想到的新選項','測試能否兼顧需要並修正'],pairs:[['差異','可以帶來新觀點的材料'],['第三選擇','由理解差異創造的新方案'],['統合綜效','共同創造比原方案更好的可能']]},
{name:'更新海岸',mentor:'瑞秋・卡森',en:'Rachel Carson',years:'1907–1964',job:'作家與生物學家',bio:'研究與書寫自然環境，以作品促進人們對生態的關注。',source:'https://www.fws.gov/staff-profile/rachel-carson-1907-1964-author-modern-environmental-movement',intro:'走了很遠，海風邀你停一停。休息不是落後；你要照顧那個一直努力走路的人。',ending:'你找到持續前行的節奏：照顧身體、心智、關係與內在價值。最後一站，讓羅盤指向自己的聲音。',steps:['察覺身體心智關係與內在的需要','選一個能補充能量的小行動','固定留時間並觀察是否有效'],pairs:[['身體更新','照顧休息、活動與身體需要'],['心智更新','主動學習與開拓觀點'],['內在更新','回到自己重視的價值與意義']]},
{name:'心聲燈塔',mentor:'弗雷德里克・道格拉斯',en:'Frederick Douglass',years:'約 1818–1895',job:'作家與演說家',bio:'透過寫作、演說與公共行動反對奴隸制度，倡議平等權利。',source:'https://www.nps.gov/people/frederick-douglass.htm',intro:'燈塔的光不要求你成為另一個人。看看你擅長的、在乎的、世界需要的，以及良知提醒你的事。',ending:'八枚碎片合成了心之羅盤。旅程沒有把你變成完美的人，而是讓你更能選擇，也替別人的聲音留位置。真正的下一關，在生活裡。',steps:['探索才能熱情需要與良知','用小行動測試自己的貢獻方向','提供支持，幫助他人找到聲音'],pairs:[['才能','我已具備或能持續培養的能力'],['熱情','讓我願意投入與探索的事'],['良知','提醒我什麼值得做及其影響']]}
];
export const links=[{title:'Habit Quest 自我領導力練功站',url:'https://habit-quest-biw.pages.dev',note:'延伸練習：概念閃卡與校園情境。'}];
export const sources=[{title:'七個習慣：FranklinCovey 官方概念',url:'https://www.franklincovey.com/courses/the-7-habits/'},{title:'第八個習慣：原書出版資訊',url:'https://www.simonandschuster.com/books/The-8th-Habit/Stephen-R-Covey/9781442350830'}];
